var activescene="";var activepreview="";var activetrans="";var studio_status="unknown";var cut_transition="";var manual_preview=!0;var trans_duration=350;var run_slider=!0;var isstreaming=!1;var isrecording=!1;function fullscreen(elem){if(elem.requestFullscreen){document.documentElement.requestFullscreen()}else if(elem.msRequestFullscreen){document.documentElement.msRequestFullscreen()}else if(elem.mozRequestFullScreen){document.documentElement.mozRequestFullScreen()}else if(elem.webkitRequestFullscreen){document.documentElement.webkitRequestFullscreen()}}
function $_GET(param){var vars={};window.location.href.replace(location.hash,'').replace(/[?&]+([^=&]+)=?([^&]*)?/gi,function(m,key,value){vars[key]=value!==undefined?value:''});if(param){return vars[param]?vars[param]:null}
return vars}
var scenes_avec_id=[];var clicked_once_pgm=0;var clicked_once_pvw=0;var btn_margin=10;var obs_ip=$_GET('ip');var disco=$_GET('disco');var password=$_GET('password');if(obs_ip==null){obs_ip="localhost"}
var obs_port=$_GET('port');if(obs_port==null){obs_port="4444"}
if(password==null){password=''}
var obs_ip_port=obs_ip+":"+obs_port;var obs=new OBSWebSocket();obs.connect({address:obs_ip_port,password:password}).then(()=>{console.log('Success! We\'re connected & authenticated.');document.getElementById("connectedto").innerHTML="Connected to: "+obs_ip_port+" | ";document.getElementsByClassName("alerte")[0].style.display="none";document.getElementsByClassName("alerte")[1].style.display="none";document.getElementsByClassName("alerte")[2].style.display="none";return obs.getSceneList({})}).then(data=>{var scene_counter=0;var scene_counter_limit=$_GET('limit');var scene_counter_limit_final=64;if(scene_counter_limit!=null){if(!isNaN(scene_counter_limit)){if(scene_counter_limit=="0"){}
else{scene_counter_limit_final=scene_counter_limit}}}
if($_GET('margin')!=null){if(!isNaN($_GET('margin'))){btn_margin=$_GET('margin')}}
data.scenes.forEach(scene=>{if(scene.name!==data.currentScene){}
if(scene_counter<scene_counter_limit_final){document.getElementById("lesboutons_PGM").innerHTML+="<input class='boutonscene classicbutton boutonscenepgm' style='margin: "+btn_margin+"px "+btn_margin+"px;' id='pgm_"+scene.name+"' onclick='switch_pgm(this);' type='submit' name='"+scene.name+"' value='"+scene.name+"'/>";document.getElementById("lesboutons_PVW").innerHTML+="<input class='boutonscene classicbutton boutonscenepvw' style='margin: "+btn_margin+"px "+btn_margin+"px;' id='pvw_"+scene.name+"' onclick='switch_pvw(this);' type='submit' name='"+scene.name+"' value='"+scene.name+"'/>";scenes_avec_id.push(scene.name)}
activescene=data.currentScene;scene_counter++;scene.sources.forEach(source=>{})});if(scenes_avec_id.includes(activescene)){redthis(document.getElementById("pgm_"+activescene))}
obs.getPreviewScene().then(function(result){activepreview=result.name;if(scenes_avec_id.includes(activepreview)){greenthis(document.getElementById("pvw_"+activepreview))}});obs.getTransitionList().then(function(result){var transitions_liste=result.transitions;cut_transition=transitions_liste[0].name;transitions_liste.forEach(trans=>{var transname_quotes='"'+trans.name+'"';document.getElementById("lesboutons_TRANS").innerHTML+="<input class='boutonscene classicbutton boutontrans' style='margin: "+btn_margin+"px "+btn_margin+"px;' id='trans_"+trans.name+"' onclick='cut("+transname_quotes+");' type='submit' name='"+trans.name+"' value='"+trans.name+"'/>"});var currenttransition=result.currentTransition;activetrans="trans_"+currenttransition;goldthis(document.getElementById(activetrans))}).then(function(){if(disco!=null){var allelems=document.querySelectorAll('.boutonscene').length;var colorbutton=["greenbutton","goldbutton","redbutton","classicbutton"];discotime();function discotime(){var alea_elem=Math.floor((Math.random()*allelems)+0);var alea_color=Math.floor((Math.random()*4)+0);document.getElementsByClassName("boutonscene")[alea_elem].classList.remove("greenbutton","goldbutton","redbutton","classicbutton");document.getElementsByClassName("boutonscene")[alea_elem].classList.add(colorbutton[alea_color]);setTimeout(discotime,10)}}});obs.GetTransitionDuration().then(function(result){trans_duration=result.transitionDuration;document.getElementById('transition_input').value=trans_duration});obs.GetStudioModeStatus().then(function(result){if(result.studioMode==!0){enablestudiomode()}
else{disablestudiomode()}})}).catch(err=>{console.log(err)});obs.onSwitchScenes(data=>{redthis(document.getElementById("pgm_"+data.sceneName));activescene=data.sceneName});obs.onPreviewSceneChanged(data=>{if(manual_preview==!0){greenthis(document.getElementById("pvw_"+data.sceneName));activepreview=data.sceneName}});obs.onSwitchTransition(data=>{goldthis(document.getElementById("trans_"+data.transitionName))});obs.onTransitionDurationChanged(data=>{trans_duration=data.newDuration;document.getElementById('transition_input').value=trans_duration});obs.onStudioModeSwitched(data=>{if(data.newState==!0){enablestudiomode()}
else{disablestudiomode()}});obs.on('Exiting',data=>{alert("OBS exited")});obs.onSceneCollectionChanged(data=>{window.location.reload()});obs.onStreamStarted(data=>{isstreaming=!0;showstreamstatus()});obs.onStreamStopped(data=>{isstreaming=!1;showstreamstatus()});obs.onRecordingStarted(data=>{isrecording=!0;showstreamstatus()});obs.onRecordingStopped(data=>{isrecording=!1;showstreamstatus()});obs.on('error',err=>{console.error('socket error:',err)});function disablestudiomode(){studio_status="disabled";document.getElementById("pvw_title").style.display="none";document.getElementById("lesboutons_PVW").style.display="none";document.getElementById("studio_status").innerHTML="Studio mode: "+studio_status+" | "}
function enablestudiomode(){studio_status="enabled";document.getElementById("pvw_title").style.display="block";document.getElementById("lesboutons_PVW").style.display="inline-block";document.getElementById("studio_status").innerHTML="Studio mode: "+studio_status+" | "}
function switch_pgm(nomdescene){if(studio_status=="enabled"){obs.SetCurrentTransition({"transition-name":cut_transition})}
else{myMove()}
clicked_once_pgm=1;obs.setCurrentScene({'scene-name':nomdescene.value})}
function switch_pvw(nomdescene){clicked_once_pvw=1;obs.SetPreviewScene({'scene-name':nomdescene.value})}
function cut(trans_type){manual_preview=!1;var transition={"with-transition":{"name":trans_type,"duration":trans_duration}};activepreview=activescene;if(studio_status=="enabled"){obs.TransitionToProgram(transition);run_slider=!0;if(trans_type==cut_transition){obs.SetPreviewScene({'scene-name':activepreview});run_slider=!1;manual_preview=!0}
else{setTimeout(function(){obs.SetPreviewScene({'scene-name':activepreview});manual_preview=!0},trans_duration)}
myMove()}
else{obs.SetCurrentTransition({"transition-name":trans_type})}}
function myMove(){var elem=document.getElementById("trans_animation_child");var width=0;var debut=new Date().getTime();if(run_slider){var id=setInterval(frame,1)};var largeur=0;function frame(){var now=new Date().getTime();if(now>=debut+trans_duration){clearInterval(id);elem.style.width="100%"}
else{largeur=((now-debut)/trans_duration)*100;elem.style.width=largeur+'%'}}}
document.getElementById("transition_input").onchange=function(){var trans_duration_input=parseInt(document.getElementById("transition_input").value);obs.SetTransitionDuration({"duration":trans_duration_input})};function redthis(elem){var boutonsscenepgm=document.getElementsByClassName("boutonscenepgm");for(var i=0;i<boutonsscenepgm.length;i++){boutonsscenepgm[i].classList.add("classicbutton")}
elem.classList.remove("classicbutton");elem.classList.add("redbutton")}
function greenthis(elem){var boutonsscenepvw=document.getElementsByClassName("boutonscenepvw");for(var i=0;i<boutonsscenepvw.length;i++){boutonsscenepvw[i].classList.add("classicbutton")}
elem.classList.remove("classicbutton");elem.classList.add("greenbutton")}
function goldthis(elem){var boutonsscenetrans=document.getElementsByClassName("boutontrans");for(var i=0;i<boutonsscenetrans.length;i++){boutonsscenetrans[i].classList.add("classicbutton")}
elem.classList.remove("classicbutton");elem.classList.add("goldbutton")}
function showstreamstatus(){if(isstreaming&&isrecording){document.getElementById("pgm_title").innerHTML="Program (<img src='images/live.gif'/> Streaming and recording)"}
else if(isstreaming&&!isrecording){document.getElementById("pgm_title").innerHTML="Program (<img src='images/live.gif'/> Streaming)"}
else if(!isstreaming&&isrecording){document.getElementById("pgm_title").innerHTML="Program (<img src='images/live.gif'/> Recording)"}
else{document.getElementById("pgm_title").innerHTML="Program"}}